"""
indice.py
----------
Everything related to the index generated by build_index.py and to
talking to Ollama for embeddings: loading vectors/metadata, requesting
the embedding of a query, comparing vectors by cosine similarity, and
formatting a product's category path (a utility shared by negacion.py
and used from search.py).

Depends on nothing else in the project except config.py.
"""

import json
import os
import sys

import numpy as np
import requests

from config.config import cargar_config

CONFIG = cargar_config()
OLLAMA_URL = CONFIG["ollama"]["url"]
EMBEDDING_MODEL = CONFIG["ollama"]["model"]


def load_index(prefix: str):
    vectors_path = f"{prefix}_vectors.npy"
    meta_path = f"{prefix}_meta.json"
    if not os.path.exists(vectors_path) or not os.path.exists(meta_path):
        sys.exit(
            f"Index '{prefix}' not found. Run build_index.py first."
        )
    vectors = np.load(vectors_path)
    with open(meta_path, encoding="utf-8") as f:
        meta = json.load(f)
    return vectors, meta


def embed_query(query: str) -> np.ndarray:
    try:
        response = requests.post(
            OLLAMA_URL,
            json={"model": EMBEDDING_MODEL, "prompt": query},
            timeout=30,
        )
    except requests.exceptions.ConnectionError:
        sys.exit(
            "Could not connect to Ollama. Is it installed and running?\n"
            "Try running 'ollama list' in another terminal to check."
        )

    if response.status_code == 404:
        sys.exit(
            f"Ollama returned 404: the model '{EMBEDDING_MODEL}' hasn't been pulled.\n"
            f"Run: ollama pull {EMBEDDING_MODEL}"
        )
    response.raise_for_status()
    return np.array(response.json()["embedding"], dtype=np.float32)


def cosine_similarity(query_vec: np.ndarray, matrix: np.ndarray) -> np.ndarray:
    query_norm = query_vec / np.linalg.norm(query_vec)
    matrix_norm = matrix / np.linalg.norm(matrix, axis=1, keepdims=True)
    return matrix_norm @ query_norm


def format_categoria(row: dict) -> str:
    return " > ".join(
        c for c in [
            row.get("categoria_nivel1", ""),
            row.get("categoria_nivel2", ""),
            row.get("categoria_nivel3", ""),
            row.get("categoria_nivel4", ""),
        ] if c
    )
